# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8573f35b44c01e0d759776d0124787de0c9ad067cd08ed2672c75727a95744281745723bb54a35527d26b6609acbc44c9b01cd80587168ca710c5d949160bfe2

test:
  secret_key_base: 5bdca9a716df19c0f7a2a797037ca1ff0451cf0520f57509d1e46e2d50190d23e4305bcbf0d7d958cd35a44db94bab0457480b375e6a18c624779500a9e602df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
